apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: fjimenez81/nginx-test10
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
      imagePullSecrets:
      - name: regcred

---

    apiVersion: v1
    kind: Service	
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      selector:
        app: nginx
      type: LoadBalancer
      #externalIPs:
      #- 192.168.99.140
      ports:
      - port: 80
        name: http
        protocol: TCP
        targetPort: 80
      - port: 443
        name: https
        protocol: TCP
        targetPort: 443
      - port: 22
        name: ssh
        protocol: TCP
        targetPort: 22